# Generated by Django 3.2.5 on 2023-12-22 12:47

import api.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='hot_TOP20',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '景点热门列表',
                'db_table': 'hot_top20',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommendforallusers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recommendations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '用户推荐列表',
                'db_table': 'recommendforallusers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='景点类型编码')),
                ('topicTranslation', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.IntegerField(blank=True, default=0, null=True, verbose_name='城市编码')),
                ('cityTranslation', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市')),
                ('low_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='最低门票')),
                ('high_price', models.IntegerField(blank=True, default=100000, null=True, verbose_name='最高门票')),
                ('address', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '景区列表',
                'db_table': 'travel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='姓名')),
                ('birth', models.DateField(null=True, verbose_name='生日')),
                ('genderCode', models.IntegerField(default='1', null=True, verbose_name='性别id 男 1 女 0')),
                ('genderTranslation', models.CharField(default='男', max_length=2, null=True, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('photo', models.ImageField(blank=True, default='default/user.jpg', null=True, upload_to=api.models.user_directory_path, verbose_name='头像')),
                ('init', models.BooleanField(blank=True, default=False, null=True, verbose_name='初始化')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city1', models.IntegerField(blank=True, default=0, null=True, verbose_name='期望城市id')),
                ('city1Translation', models.CharField(blank=True, max_length=20, null=True, verbose_name='期望城市')),
                ('city2', models.IntegerField(blank=True, default=0, null=True, verbose_name='期望城市2id')),
                ('city2Translation', models.CharField(blank=True, max_length=20, null=True, verbose_name='期望城市2')),
                ('city3', models.IntegerField(blank=True, default=0, null=True, verbose_name='期望城市3id')),
                ('city3Translation', models.CharField(blank=True, max_length=20, null=True, verbose_name='期望城市3')),
                ('topic', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='期望景点类型编码')),
                ('topicTranslation', models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='期望景点类型')),
                ('low_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='期望最低经费')),
                ('high_price', models.IntegerField(blank=True, default=100000, null=True, verbose_name='期望最高经费')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户画像信息',
                'verbose_name_plural': '用户画像信息',
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='StarTravel',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.travel', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏列表',
                'db_table': 'star',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('lid', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.TextField(verbose_name='行为')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='ClickTravel',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.travel', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览列表',
                'db_table': 'click',
            },
        ),
    ]
