# Generated by Django 3.2.5 on 2023-12-25 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_resume_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTravel',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.travel', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论列表',
                'db_table': 'comment',
            },
        ),
    ]
